### ISSUE TITLE
Activate codeclimate for the gem

### ISSUE THREAD

**Issue by aaronmallen** [dhiemstra/esi#24]
Lets start monitoring our maintainability and our test coverage.

- [x] @dhiemstra https://codeclimate.com/github/repos/new go here and setup the repo for codeclimate.
- [x] @dhiemstra add the `CC_TEST_REPORTER_ID` variable to travis using the `TEST REPORTER ID` found in Repo Settings > Test Coverage on the codeclimate project
- [x] @dhiemstra add the maintainability badge and test coverage badge to the README found in Settings > Badges on the code climate test reporter
- [x] @dhiemstra install webhook and pull request integerations found in Repo Settings > Git Repository on the codeclimate project
- [x] @dhiemstra setup github issues by going to Repo Settings > Integrations and clicking "Edit" on `GitHub Issues` (see comments below)
- [x] @dhiemstra setup github pull requests by going to Repo Settings > Integrations and clicking "Edit" on GitHub Pull Requests (see comments below)
- [x] @aaronmallen add simplecov to the test suite to report coverage.
- [x] @aaronmallen generate the codeclimate configuration for the gem
- [x] @aaronmallen add coverage reporting to the `.travis.yml`
- [x] @aaronmallen after the first successful CC report open stories to improve our coverage and maintainability.
- [x] @aaronmallen open up issues for codeclimate maintainablity

**Comment by dhiemstra** [comment]
Should be done

Met vriendelijke groet,

*Danny Hiemstra*
Founder/CEO Salonized

Herengracht 575
1017 CD Amsterdam
(+31) 020-8932386
www.salonized.com

**Comment by aaronmallen** [comment]
@dhiemstra I've added two new tasks for you to this ticket.  On the codeclimate project goto: 

Repo Settings > Integrations and click "edit" on GitHub Issues... you will need to create a personal access token for this (you can do that [here](https://github.com/settings/tokens)).  Put 

* the github token in the `Token` input
* `dhiemstra/esi` in the `Project` input
* `codeclimate` in the `Labels` input

Click save and then click the `Test Service` button next to the GitHub Issues integration

do pretty much the same thing for the `GitHub Pull Requests` integration and then @ mention me here when its done and I'll close this issue out.  Thanks a bunch for setting this up, it will really help us monitor our code coverage/maintainability.

**Comment by aaronmallen** [comment]
@dhiemstra bump

**Comment by aaronmallen** [comment]
actually scratch that bump... it looks like this is all implemented and working as expected, I just don't have the appropriate access to open up issues from codeclimate, which is fine.
